apiVersion: v1
kind: ConfigMap
metadata:
  name: fl-client-config
  namespace: federated-learning
data:
  k8s-client.yaml: |
    dataset:
      type: "5gnidd"
      test_size: 0.2
      seed: 42
      data_dir: "./data"
    
    num_clients: 10
    batch_size: 8
    num_classes: 10
    
    attack:
      enabled: true
      attack_type: "label_flip"
      malicious_ratio: 0.5
      attack_params:
        target_layers: "all"
        layer_specific_factor: 1.0
        attack_probability: 0.8
        attack_start_round: 3
        poison_global_model: false
        poisoning_method: "gaussian"
        constant_noise:
          constant_noise_value: 1.5
        scale:
          scale_factor: 1.6
        invert: {}
        gaussian: {}
        label_flip:
          num_classes: 10
          flip_ratio: 1.0
          target_label: 0
          source_labels: [2, 4, 5, 7]
          flip_strategy: "targeted"