apiVersion: v1
kind: ConfigMap
metadata:
  name: fl-server-config
  namespace: federated-learning
data:
  k8s-server.yaml: |
    dataset:
      type: "5gnidd"
      test_size: 0.2
      seed: 42
      data_dir: "./data"
    
    num_rounds: 20
    num_clients: 10
    batch_size: 8
    num_classes: 10
    
    server:
      port: 8080
      fraction_fit: 1.0
      fraction_evaluate: 1.0
      min_fit_clients: 8
      min_evaluate_clients: 5
      min_available_clients: 5
    
    config_fit:
      lr: 0.01
      momentum: 0.9
      local_epochs: 5